### ISSUE TITLE
EWS does not have scipy.spatial

### ISSUE THREAD

**Issue by ijustlovemath** [Atrifex/ECE385-HelperTools#1]
So no native KDTree. Ideas?

**Comment by atrifex** [comment]
I seem to no be able to reproduce this issue. Can you take a screenshot and post it here so that I can know the exact issue?

**Comment by ijustlovemath** [comment]
![here you go](http://i.imgur.com/MwOGohK.jpg)

**Comment by atrifex** [comment]
Okay so you need to be on a windows ews computer. They have the libraries that you need to do this. 

You can also work from your own computer by using something called **pip** to install the libraries that are needed. You can read more about pip and how to install it here: https://pip.pypa.io/en/stable/installing/

**Comment by atrifex** [comment]
I am going to go ahead and close this issue. 

If you keep having problems, you can go ahead and open at again.
