### ISSUE TITLE
Could not Find Image

### ISSUE THREAD

**Issue by mmogallapalli** [Atrifex/ECE385-HelperTools#6]
Hi Rishi,

I was using the relative resizer script for our project and ran into a problem. 

I downloaded all of the necessary modules and stuff and when I try to find the picture it is giving me the following error:

![unnamed](https://cloud.githubusercontent.com/assets/15723785/20725308/f397cb4c-b636-11e6-914d-0394c6abd37c.png)

I tried to use the images that you left in the folder and it was giving the same error then as well. Do you have any ideas as to why I am getting this error?

**Comment by atrifex** [comment]
What OS are you using?

**Comment by mmogallapalli** [comment]
MacOS

**Comment by atrifex** [comment]
The problem seems to just be that you are either typing your file name incorrectly or that it does not exist in that directory. Can you add a picture of your directory structure?

**Comment by mmogallapalli** [comment]
<img width="839" alt="screen shot 2016-11-29 at 2 59 15 pm" src="https://cloud.githubusercontent.com/assets/15723785/20728684/74ce6e52-b644-11e6-9894-69d1c1f72f76.png">

**Comment by atrifex** [comment]
Why are you not using the dispatcher script?

**Comment by mmogallapalli** [comment]
What is the dispatcher script?

**Comment by atrifex** [comment]
The png_to_txt.py dispatcher script is part of the new update and should be used instead of the script directly.

You will need to make a couple of changes though. 
Every where you see:
`        os.system("python <DIRECTORY>")
`
Change it to:
`        os.system("python3 <DIRECTORY>")
`

**Comment by atrifex** [comment]
This I believe will fix your issue. 

I am going to close the issue. If you have any more problems, then you can reopen the issue or you can create a new one.

**Comment by mmogallapalli** [comment]
I am still getting the same issue even after I am using the png_to_txt.py and made the change from python to python3

<img width="931" alt="screen shot 2016-11-29 at 6 21 57 pm" src="https://cloud.githubusercontent.com/assets/15723785/20734688/bf819d5e-b660-11e6-882f-13f58f11da91.png">
