### ISSUE TITLE
Image Finding Issue

### ISSUE THREAD

**Issue by mmogallapalli** [Atrifex/ECE385-HelperTools#7]
I am still getting the same issue even after I am using the png_to_txt.py and made the change from python to python3
<img width="931" alt="screen shot 2016-11-29 at 6 21 57 pm" src="https://cloud.githubusercontent.com/assets/15723785/20734719/f7e1fb94-b660-11e6-94f7-f6599458c957.png">

**Comment by atrifex** [comment]
Here is what the output should look like when you run the script:

<img width="1280" alt="screen shot 2016-11-29 at 6 27 31 pm" src="https://cloud.githubusercontent.com/assets/12935724/20734812/9272475e-b661-11e6-99f4-a629d09a90e8.png">

You are not running the dispatcher as I said before.

**Comment by atrifex** [comment]
Did that fix the issue?

**Comment by mmogallapalli** [comment]
Yeah I just got it to work thanks!

**Comment by atrifex** [comment]
Great!
