### ISSUE TITLE
Regarding to your PNG_to_Txt Program

### ISSUE THREAD

**Issue by xyang70** [Atrifex/ECE385-HelperTools#8]
Hi, I am trying to use your program, after I typed in mode 2, it prompted me to enter the file name. I tried to enter my PNG file name, and it outputs this:
What's the image name? 80elephant
Traceback (most recent call last):
  File "./scripts/png_to_palette_resizer.py", line 11, in <module>
    filename = input("What's the image name? ")
  File "<string>", line 1
    80elephant
             ^
SyntaxError: unexpected EOF while parsing

And I tried to use the image you already had, it outputed me this:
Traceback (most recent call last):
  File "./scripts/png_to_palette_resizer.py", line 11, in <module>
    filename = input("What's the image name? ")
  File "<string>", line 1, in <module>
NameError: name 'Right' is not defined

So do I need to install something on my computer or not? Thanks.

**Comment by atrifex** [comment]
You will need to make a couple of change one thing in the file. The file is optimized for working on the EWS computers. You have make a small change to get it to work correctly on your own computer.

Every where you see:
`os.system("python <DIRECTORY>")`
Change it to:
`os.system("python3 <DIRECTORY>")`

**Comment by atrifex** [comment]
I am assuming that this issue has been resolved and those am closing it. Please feel free to reopen the issue if you are still having trouble.
